# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Justin Delano
email: jdelano[at]g.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  First Year Ph.D. student studying Bioinformatics and Integrative Genomics at Harvard Medical School
baseurl: "" # the subpath of your site, e.g. /blog
url: http://justindelano.com # the base hostname & protocol for your site, e.g. http://example.com
logo: favicon.ico

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

include: ["_includes", "_pages", "_layouts"]

minimal_mistakes_skin: dark
search: false
search_full_content: true
atom_feed:
  hide: true

author:
  name        : "Justin Delano"
  bio         : "First Year Ph.D. student studying Bioinformatics and Integrative Genomics at Harvard Medical School"
  avatar      : "/assets/images/BW_Profile.jpg"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jdelano@g.harvard.edu"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/justindelano_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/justin-delano-337394156/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justin-delano"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/justindelano_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/justin-delano-337394156/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justin-delano"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        teaser: /assets/images/SingleDNA.png
        og_image: /assets/images/SingleDNA.png


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - workspace.code-workspace
  - README.md